<?php

return [
    'default' => [
        [
            'key'            => 'signin',
            'value'          => 'Signin',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'logout',
            'value'          => 'Logout',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'signup',
            'value'          => 'Signup',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'setting',
            'value'          => 'Setting',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'sign_up',
            'value'          => 'Sign Up',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'sign_in',
            'value'          => 'Sign In',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'profile',
            'value'          => 'Profile',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'show_profile',
            'value'          => 'Show Profile',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'change_password',
            'value'          => 'Change Password',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'edit_profile',
            'value'          => 'Edit Profile',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'back',
            'value'          => 'Back',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'update_profile',
            'value'          => 'Update Profile',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'first_name',
            'value'          => 'First Name',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'last_name',
            'value'          => 'Last Name',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'full_name',
            'value'          => 'Full Name',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'phone_number',
            'value'          => 'Phone Number',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'dob',
            'value'          => 'DOB',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'email',
            'value'          => 'Email',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'forgot_password',
            'value'          => 'Forgot Password',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'password',
            'value'          => 'Password',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'old_password',
            'value'          => 'Old Password',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'new_password',
            'value'          => 'New Password',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'confirm_password',
            'value'          => 'Confirm Password',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'have_account',
            'value'          => 'Already have an account ?',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'do_not_have_account',
            'value'          => 'Do not have an account ?',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'create_new_account',
            'value'          => 'Create New Account',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'welcome',
            'value'          => 'Welcome',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],

        [
            'key'            => 'welcome_back',
            'value'          => 'Welcome Back !',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'login_success',
            'value'          => 'You have logged in successfully!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'only_admin_access',
            'value'          => 'Only admin can access!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'cred_error',
            'value'          => 'You have entered wrong credentials!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'email_verify_first',
            'value'          => 'You need to verify your email address first!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'update_success',
            'value'          => 'Your profile updated successfully!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'sent',
            'value'          => 'We have emailed your password reset link!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'reset',
            'value'          => 'Your password has been reset!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'throttled',
            'value'          => 'Please wait before retrying!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'token',
            'value'          => 'This password reset token is invalid!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'user',
            'value'          => "We can't find a user with that email address!",
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'error_message',
            'value'          => "Something went wrong....please try again later!",
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'password_change',
            'value'          => "Your password has been changed!",
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'reset_password',
            'value'          => 'Reset Password',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'instructions',
            'value'          => 'Enter your email and instructions will be sent to you!',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'send_reset_link',
            'value'          => 'Send Reset Link',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'remember_password',
            'value'          => 'Wait, I remember my password... ',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'click_here',
            'value'          => 'Click here ',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'pssword_diffrent',
            'value'          => 'Your new password must be different from previous used password',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'free_account',
            'value'          => 'Get your free velzon account now',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],

        [
            'key'            => 'Signin_to_comtinue',
            'value'          => 'Sign in to continue to Forex.',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'language',
            'value'          => 'Language',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'admin',
            'value'          => 'Admin',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'list',
            'value'          => 'List',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'add',
            'value'          => 'Add',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'sno',
            'value'          => 'S. No.',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'name',
            'value'          => 'Name',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'code',
            'value'          => 'Code',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'createdat',
            'value'          => 'Created At',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'status',
            'value'          => 'Status',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'action',
            'value'          => 'Action',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'search',
            'value'          => 'search...',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'previous',
            'value'          => 'Previous',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'next',
            'value'          => 'Next',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'active',
            'value'          => 'Active',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'deactive',
            'value'          => 'Deactive',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'data_not_found',
            'value'          => 'Sorry! No Result Found',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'add_language',
            'value'          => 'Add Language',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'image',
            'value'          => 'Image',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'close',
            'value'          => 'Close',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'update_language',
            'value'          => 'Update Language',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'edit_language',
            'value'          => 'Edit Language',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'added_success',
            'value'          => 'Added Successfully',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'updated_success',
            'value'          => 'Updated Successfully',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'delete_success',
            'value'          => 'Deleted Successfully',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'change_status',
            'value'          => 'Status Change Successfully',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'data_already_exist',
            'value'          => 'Data Already Exist',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],



        [
            'key'            => 'email_required',
            'value'          => 'The email field is required.',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'password_required',
            'value'          => 'The password field is required.',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],
        [
            'key'            => 'valid_email_address',
            'value'          => 'The email field must be a valid email address.',
            'language_id'    =>  1,
            'created_at'     => date('Y-m-d H:i:s'),
            'updated_at'     => date('Y-m-d H:i:s'),
        ],





    ],

];
